#!/bin/sh /etc/rc.common
. /usr/share/libubox/jshn.sh
. /lib/functions.sh

START=96
USE_PROCD=1

CONF="oafd"
PROG="/usr/bin/oafd"

FEATURE_FILE="/tmp/feature.cfg"
CLASS_FILE="/tmp/app_class.txt"

service_triggers()
{
	procd_add_reload_trigger "oafd"
}

stop_service(){
	killall -9 oafd
	rmmod oaf
}

start_service(){
	config_load $CONF

	config_get_bool enable "global" "enable" "0"

	[ "$enable" == "0" ] && exit 0

	[ -f $FEATURE_FILE ] && rm -f $FEATURE_FILE
	[ -f $CLASS_FILE ] && rm -f $CLASS_FILE

	config_get update "feature" "update"
	if [ x"1" == x"$update" ];then
		ln -s /etc/oafd/feature.cfg $FEATURE_FILE
	else
		ln -s /etc/oafd/feature_en.cfg $FEATURE_FILE
	fi

	oafd_gen_class.sh $FEATURE_FILE
	insmod oaf
	/usr/bin/oafd_rule reload

	config_get lan_if "global" "lan_if"
	echo $lan_if > /proc/sys/oaf/lan_if

	procd_open_instance
	procd_set_param respawn 60 5 5
	procd_set_param stderr 1
	procd_set_param command "$PROG" -I $lan_if
	procd_close_instance
}
