/*
 * Copyright (C) 2026 Optim Enterprises BV
 *
 * This is free software, licensed under the BSD 3-Clause License.
 */

#include "nft.h"

#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

const char *nft_reject_str(enum nft_reject r)
{
	switch (r) {
	case NFT_OK:
		return "ok";
	case NFT_REJECT_MALFORMED:
		return "malformed";
	case NFT_REJECT_PREFIX:
		return "prefix_out_of_range";
	case NFT_REJECT_TOO_BROAD:
		return "too_broad";
	case NFT_REJECT_HOSTBITS:
		return "host_bits_set";
	case NFT_REJECT_UNSAFE_CHARS:
		return "unsafe_characters";
	default:
		return "unknown";
	}
}

/* Only characters that can appear in an IPv4/IPv6 address or prefix. Anything
 * else -- a space, a semicolon, a brace, a backtick -- is refused here rather
 * than left for inet_pton to reject incidentally. */
static bool safe_chars(const char *s, size_t *len_out)
{
	size_t n = 0;
	for (const char *p = s; *p; p++, n++) {
		if (n > NFT_ELEM_TEXT_MAX)
			return false;
		char c = *p;
		bool ok = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') ||
		          (c >= 'A' && c <= 'F') || c == '.' || c == ':' || c == '/';
		if (!ok)
			return false;
	}
	*len_out = n;
	return n > 0;
}

/* Are any bits set below `prefix`? A feed entry like 10.1.2.3/8 is ambiguous:
 * it may mean the host or the network. Refusing it beats guessing, because the
 * two readings differ by 16.7 million addresses. */
static bool has_host_bits(const uint8_t *addr, uint8_t bytes, uint8_t prefix)
{
	for (uint8_t i = 0; i < bytes; i++) {
		uint8_t keep;
		if (prefix >= (uint8_t)((i + 1) * 8))
			keep = 0xFF;
		else if (prefix <= (uint8_t)(i * 8))
			keep = 0x00;
		else
			keep = (uint8_t)(0xFF << (8 - (prefix - (uint8_t)(i * 8))));
		if (addr[i] & (uint8_t)~keep)
			return true;
	}
	return false;
}

enum nft_reject nft_elem_parse(const char *text, struct nft_elem *out)
{
	if (!text || !out)
		return NFT_REJECT_MALFORMED;

	size_t len = 0;
	if (!safe_chars(text, &len))
		return NFT_REJECT_UNSAFE_CHARS;

	char buf[NFT_ELEM_TEXT_MAX + 1];
	memcpy(buf, text, len);
	buf[len] = '\0';

	char *slash = strchr(buf, '/');
	long prefix = -1;
	if (slash) {
		*slash = '\0';
		char *endp = NULL;
		prefix = strtol(slash + 1, &endp, 10);
		if (!endp || *endp != '\0' || prefix < 0)
			return NFT_REJECT_MALFORMED;
	}

	memset(out, 0, sizeof(*out));

	if (inet_pton(AF_INET, buf, out->addr) == 1) {
		out->family = 4;
		out->prefix = (uint8_t)(slash ? prefix : 32);
		if (out->prefix > 32)
			return NFT_REJECT_PREFIX;
		if (out->prefix < NFT_MIN_PREFIX_V4)
			return NFT_REJECT_TOO_BROAD;
		if (has_host_bits(out->addr, 4, out->prefix))
			return NFT_REJECT_HOSTBITS;
		return NFT_OK;
	}

	if (inet_pton(AF_INET6, buf, out->addr) == 1) {
		out->family = 6;
		out->prefix = (uint8_t)(slash ? prefix : 128);
		if (out->prefix > 128)
			return NFT_REJECT_PREFIX;
		if (out->prefix < NFT_MIN_PREFIX_V6)
			return NFT_REJECT_TOO_BROAD;
		if (has_host_bits(out->addr, 16, out->prefix))
			return NFT_REJECT_HOSTBITS;
		return NFT_OK;
	}

	return NFT_REJECT_MALFORMED;
}

size_t nft_elem_render(const struct nft_elem *e, char *out, size_t out_len)
{
	if (!e || !out || out_len == 0)
		return 0;
	if (e->family != 4 && e->family != 6)
		return 0;

	char addr[INET6_ADDRSTRLEN];
	int af = (e->family == 4) ? AF_INET : AF_INET6;
	if (!inet_ntop(af, e->addr, addr, sizeof(addr)))
		return 0;

	int n;
	if (e->timeout_sec > 0)
		n = snprintf(out, out_len, "%s/%u timeout %us", addr, e->prefix,
		             e->timeout_sec);
	else
		n = snprintf(out, out_len, "%s/%u", addr, e->prefix);

	if (n < 0 || (size_t)n >= out_len)
		return 0;
	return (size_t)n;
}

size_t nft_render_set_decl(const struct nft_target *t, uint32_t default_timeout_sec,
                           char *out, size_t out_len)
{
	if (!t || !out || out_len == 0)
		return 0;

	/*
	 * `flags interval` is required for prefixes rather than bare addresses,
	 * and `auto-merge` collapses overlapping entries so a feed shipping both
	 * 1.2.0.0/16 and 1.2.3.0/24 does not error on insert.
	 *
	 * `timeout` makes decay the kernel's job: an entry nobody refreshes ages
	 * out on its own, so a controller that stops publishing stops blocking
	 * rather than leaving a stale set enforcing forever.
	 */
	int n = snprintf(
	    out, out_len,
	    "# Generated by aether-sensord. Do not edit.\n"
	    "# Declared in an fw4 include so it survives `fw4 reload` -- a set\n"
	    "# created with `nft add set` is destroyed the next time fw4 rebuilds.\n"
	    "table %s %s {\n"
	    "\tset %s {\n"
	    "\t\ttype ipv4_addr\n"
	    "\t\tflags interval,timeout\n"
	    "\t\tauto-merge\n"
	    "\t\ttimeout %us\n"
	    "\t}\n"
	    "\tset %s {\n"
	    "\t\ttype ipv6_addr\n"
	    "\t\tflags interval,timeout\n"
	    "\t\tauto-merge\n"
	    "\t\ttimeout %us\n"
	    "\t}\n"
	    "}\n",
	    t->family, t->table, t->set_v4, default_timeout_sec, t->set_v6,
	    default_timeout_sec);

	if (n < 0 || (size_t)n >= out_len)
		return 0;
	return (size_t)n;
}

static size_t render_batch(const struct nft_target *t, const char *verb,
                           const struct nft_elem *elems, size_t n, char *out,
                           size_t out_len, size_t *n_rendered)
{
	if (n_rendered)
		*n_rendered = 0;
	if (!t || !verb || !elems || !out || out_len == 0)
		return 0;
	if (n > NFT_BATCH_MAX)
		n = NFT_BATCH_MAX;

	size_t used = 0;
	size_t done = 0;

	for (int pass = 0; pass < 2; pass++) {
		uint8_t fam = (pass == 0) ? 4 : 6;
		const char *set = (pass == 0) ? t->set_v4 : t->set_v6;

		size_t count = 0;
		for (size_t i = 0; i < n; i++)
			if (elems[i].family == fam)
				count++;
		if (count == 0)
			continue;

		int w = snprintf(out + used, out_len - used, "%s element %s %s %s { ",
		                 verb, t->family, t->table, set);
		if (w < 0 || (size_t)w >= out_len - used)
			return 0;
		used += (size_t)w;

		bool first = true;
		for (size_t i = 0; i < n; i++) {
			if (elems[i].family != fam)
				continue;

			char text[NFT_ELEM_TEXT_MAX];
			/* `delete` must not carry a timeout -- nft rejects it. */
			struct nft_elem e = elems[i];
			if (verb[0] == 'd')
				e.timeout_sec = 0;
			if (nft_elem_render(&e, text, sizeof(text)) == 0)
				continue; /* unrenderable: skip, never emit partial */

			w = snprintf(out + used, out_len - used, "%s%s",
			             first ? "" : ", ", text);
			if (w < 0 || (size_t)w >= out_len - used)
				return 0;
			used += (size_t)w;
			first = false;
			done++;
		}

		w = snprintf(out + used, out_len - used, " }\n");
		if (w < 0 || (size_t)w >= out_len - used)
			return 0;
		used += (size_t)w;
	}

	if (n_rendered)
		*n_rendered = done;
	return used;
}

size_t nft_render_add(const struct nft_target *t, const struct nft_elem *elems,
                      size_t n, char *out, size_t out_len, size_t *n_rendered)
{
	return render_batch(t, "add", elems, n, out, out_len, n_rendered);
}

size_t nft_render_del(const struct nft_target *t, const struct nft_elem *elems,
                      size_t n, char *out, size_t out_len, size_t *n_rendered)
{
	return render_batch(t, "delete", elems, n, out, out_len, n_rendered);
}

size_t nft_render_flush(const struct nft_target *t, char *out, size_t out_len)
{
	if (!t || !out || out_len == 0)
		return 0;
	int n = snprintf(out, out_len,
	                 "flush set %s %s %s\n"
	                 "flush set %s %s %s\n",
	                 t->family, t->table, t->set_v4, t->family, t->table,
	                 t->set_v6);
	if (n < 0 || (size_t)n >= out_len)
		return 0;
	return (size_t)n;
}
