/*
 * Copyright (C) 2026 Optim Enterprises BV
 *
 * This is free software, licensed under the BSD 3-Clause License.
 *
 * Loading a policy database from a UCI configuration file.
 *
 * ADR-020 decision 10 pins the local config surface on OpenWrt and prplOS to
 * UCI, so that is what this reads. It parses the UCI file format directly
 * rather than linking libuci -- the same reasoning as nflog_raw.c: the format
 * is small and stable, and a dependency-free parser keeps this binary's
 * declared licence true and lets the whole thing be tested on a host with no
 * device, no ubus and no root.
 *
 * WHAT THIS REFUSES IS THE POINT. A policy file is written by a human or
 * generated by a controller, and either can get it wrong. Every line this
 * cannot use is counted and reported by category. A rule naming an unknown
 * application, a malformed MAC, a window outside 0..1439 -- each of those is a
 * rule that will never fire, and a loader that skipped them quietly would
 * produce a device that reports healthy while enforcing nothing (ADR-017).
 */

#ifndef AETHER_SENSORD_POLCFG_H
#define AETHER_SENSORD_POLCFG_H

#include "policy.h"
#include "sigdb.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

/* Why a line was not used. Counted separately so the report distinguishes
 * "the file is corrupt" from "this device does not know that app". */
struct polcfg_stats {
	uint32_t sections;          /* config sections seen */
	uint32_t subjects_added;
	uint32_t rules_added;

	uint32_t bad_syntax;        /* line was not parseable UCI */
	uint32_t unknown_section;   /* config type we do not implement */
	uint32_t unknown_option;    /* option key we do not implement */
	uint32_t bad_mac;           /* subject/rule MAC unparseable */
	uint32_t bad_window;        /* window values out of range or malformed */
	uint32_t bad_action;        /* action neither block nor allow */
	uint32_t missing_tag;       /* rule section with no tag */
	uint32_t unknown_subject;   /* rule names a MAC with no subject section */
	/*
	 * Rule named no subject at all. The policy engine is per-subject and
	 * has no "all devices" index, so a house-wide rule cannot currently be
	 * expressed. Counted rather than approximated -- see polcfg.c.
	 */
	uint32_t no_subject;
	uint32_t refused_by_policy; /* pol_add_* refused: capacity or unknown tag */
};

/* True if anything at all was refused. Callers use this to decide whether the
 * loaded policy can be trusted to mean what the file says. */
bool polcfg_had_refusals(const struct polcfg_stats *s);

/*
 * Parse UCI text into `db`.
 *
 * `sigs` may be NULL to skip tag validation, but should not be in production:
 * with it, a rule naming an application this device has no signatures for is
 * refused and counted rather than accepted and silently never matched.
 *
 * Returns the number of rules added, or -1 if `text` or `db` is NULL. A file
 * that parses but yields nothing returns 0 -- which is a legitimate state
 * (no policy configured) and is deliberately distinct from an error.
 */
long polcfg_parse(struct pol_db *db, const struct sig_db *sigs,
                  const char *text, size_t len, struct polcfg_stats *stats);

/* As above, reading from a path. Returns -1 if the file cannot be opened. */
long polcfg_load_file(struct pol_db *db, const struct sig_db *sigs,
                      const char *path, struct polcfg_stats *stats);

/* Write a one-line-per-category summary of what was refused. */
void polcfg_report(const struct polcfg_stats *s,
                   void (*emit)(void *user, const char *line), void *user);

#endif /* AETHER_SENSORD_POLCFG_H */
